[package]
name = "fusion_mouse"
version = "0.1.0"
authors = ["Tristan Hume <tristan@thume.ca>"]

[dependencies]
linuxtrack-sys = "1.0.1"
cgmath = "0.15"
enigo = {git="https://github.com/trishume/enigo"}
tobii-sys = "0.1.0"
signpost = {git="https://github.com/pcwalton/signpost"}

piston = "0.35.0"
piston2d-graphics = "0.24.0"
piston2d-glium_graphics = "0.46.0"
glutin = "0.10.1"
cocoa = "0.9.2"
objc = "0.2.2"
