[package]
name = "fusion_mouse"
version = "0.1.0"
authors = ["Tristan Hume <tristan@thume.ca>"]

[dependencies]
linuxtrack-sys = "1.0.1"
cgmath = "0.15"
enigo = {path="../enigo"}
tobii-sys = {path="../tobii-sys"}
signpost = {git="https://github.com/pcwalton/signpost"}
